### ISSUE TITLE
Why is Observable.context not a DictField of DictField ?

### ISSUE THREAD

**Issue by trolldbois** [yeti-platform/yeti#106]
### Description
Discussion on the type of Observable.context.
Why is it not a DictField of DictField instead of ListField of DictField ?

It's a question, not a bug report or a feature request (if you don't like it)

Declared in https://github.com/yeti-platform/yeti/blob/master/core/observables/observable.py#L43
`context = ListField(DictField(), verbose_name="Context")`

But in https://github.com/yeti-platform/yeti/blob/master/core/observables/observable.py#L147
`assert 'source' in context`
which basically means every context needs a name.

In that case it would be more "dev-friendly" to change interfaces to something that has a name
`def add_context(self, context_name, context, replace_source=None):`
`def remove_context(self, context_name):`

But that also mean the Observable.context is actually Obervable.contexts, with an 's'
`    contexts = DictField(DictField(), verbose_name="Contexts")`

The net effect of that change is that when a feed loads Observables and sets their context, 

1. the code would be cleaner to "update" a context with new information.

new form:

    context = {'source': context_name}
    if context_name in my_url.contexts:
        context = my_url.contexts[context_name]
    context.update(new_context_info)
    my_url.save()

instead of 

    context = {'source': context_name}
    contexts = dict.fromkeys([c['source'] for c in my_url.context])
    if context_name in contexts:
        context = [c for c in my_url.context if c['source'] == context_name][0]
    context.update(new_context_info)
    my_url.save()

mmhh, ok, I kinda disproved the point on code complexity i was trying to make.
But ultimately, if context must have names, why not use a Dict to force name unicity ?

2. There wouldn't be any duplicate context-es with the same source name (due to bad code)

**Comment by tomchop** [comment]
Yes, using the source name as a key to a dict crossed our minds, but IIRC using an array makes it easier to build search queries on context data.

You can query for `db.observables.find({context.subdata: "something"})` and if one of the `context` sub-documents has a subdata member set to `something`, it will return that document. This is useful to query for contextual data when you do not know the source. (otherwise, AFAIK, you would have to do `db.observable.find({context.<SOURCE_NAME>.subdata: "something"})`.

You could argue that there are not that many `subdata` fields which exist across `context` subdocuments, but I still think the ability to query for those easily is worth the extra complexity which is not that huge.

**Comment by gaelmuller** [comment]
I agree, this is simpler in order to build queries and the source is not unique (we can have several contexts for the same source), so I will close this.
