### ISSUE TITLE
DB Data not accessible ... again.

### ISSUE THREAD

**Issue by TQPS** [yeti-platform/yeti#1110]
### Description
After updating to most recent commits in both yeti and yeti-docker I am no longer able to log into Yeti with default username & password.

Logging into Arangodb I can see that no documents are appearing.

I believe, some time ago, a commit was made to make data consistent and persist during reboots and restarts - to /yeti-data(?)

How do I ensure that my data - which still appears to be in /yeti-data - is accessible and persistent across updates and restarts?

### Environment

| Question                  | Answer
|---------------------------|--------------------
| Yeti release              | 2.1.9
| Yeti-frontend release     | ? whatever latest is
| OS version                | Ubuntu 22.04
| Browser                   | Firefox 128.0

### Steps to Reproduce
```
cd /opt/yeti
sudo git pull
cd prod
docker compose pull
docker compose up
```
- Open browser, login to Yeti - get an error "Incorrect username or password" - cannot log in - locked out
- Check Arangodb users - document size 0
- Check Arangodb entities - document size 0

#### Expected behavior
Expect that my data is accessible - even from the docker environment - across repeated and consistent updates and reboots.

#### Actual behavior
- Cannot log in due to db data not being available or accessible.
- No apparent errors - there IS a default db - just with nothing in it

**Comment by tomchop** [comment]
We recently changed the docker compose file to use docker volumes instead of an arbitrary volume on the disk: https://github.com/yeti-platform/yeti-docker/pull/14/files

You can do

```
docker volume inspect yeti-exports
docker volume inspect yeti-db
```

To check where they're mounted on your local filesystem, and copy the data from `/yeti-data` there.

Another note: we don't update the docker compose file very regularly, so when it happens please make sure to check the changes so that you're not breaking your install. For this specific change, we even added some tips to the readme on how to sucesfully upgrade: https://github.com/yeti-platform/yeti-docker/blob/main/README.md.
