### ISSUE TITLE
Feature Request: Static Investigation Graph versus Elastic

### ISSUE THREAD

**Issue by scrublullz** [yeti-platform/yeti#159]
Good Afternoon -  
  
I wanted to put a request in to change the behavior, or add the option, to allow items to be dragged and dropped in a location versus the rubber band that currently happens. I am thinking something like Maltego to make visual analysis a bit easier.  
  
Thank you for your consideration!

**Comment by tomchop** [comment]
Have you tried the "Cycle through layouts" option in the investigation panel?

Otherwise, I think it's fairly easy to change the rubber band behavior, although making the it dynamic (i.e. letting the user choose the behavior) is a bit trickier.

Also, I assume that if you want to place items, you'd want to keep them in the same place even when you reload the investigation? THAT will require a bit more work.

**Comment by scrublullz** [comment]
Thank you @tomchop 

I have used the cycle option, but I am looking to drag an item to a location and set it and leave it.

I would prefer the ability to save the location of items in between views and return to them.  It would still be nice to cycle through layouts or have YETI re-order items systematically, too.

**Comment by tomchop** [comment]
Gotcha. Saving the node positions is feasible but nontrivial. @gaelmuller, WDYT?

**Comment by gaelmuller** [comment]
I agree that this would be better.It is not difficult to do temporarily, but I'm not sure we would be able to save the node positions. I would have to research this.
