### ISSUE TITLE
Large number of Feeds (via Pull Requests)

### ISSUE THREAD

**Issue by darksheer** [yeti-platform/yeti#203]
### Description
Over the holiday break, I created about 78 additional feeds to be ingested into Yeti.  I'm _more_ than happy to start submitting pull requests, but I wanted to check with you on some potential problems before I do so. 

If these feeds should be submitted to core, there might need to be a feature to turn feeds on/off and will also need the ability to specify API keys. 

If core isn't the right answer, perhaps a non-core repo of feed scripts would be worthwhile.  That way end users could select to pull in community created feeds, rather than having them all in core. It would also be nice to have some feeds for paid for TI services pre-built and ready for an API key.  I haven't built any yet, but I'm sure others have, so having the ability to let the script sit without the necessary API key would be a great community sharing opportunity (MISP / TAXII feeds are an example of this).  

Lemme know what you think and I can finish up testing and get the PR's over to you. I have dozens more that I'll be working on to start pulling in (some pub, some not). 

As a side note, adding this many additional feeds has pushed the memory consumption of yet to the north of 5.5 GB's and average Disk I/O to an average of 5 mb's for Mongo.

I did double the number of Feed and Analytics workers from the default.  I don't think I've hit the limits of the instance (36 Cores / 60 GB of Mem), but Yeti is definitely beginning to push it. I'm considering deploying a large MongoDB cluster, rather than the local install, but past experience of managing MongoDB tells me I'm setting myself up for a management nightmare. 

Applicable screenshot:
![image](https://user-images.githubusercontent.com/1522288/34368503-659f9c76-ea69-11e7-86a4-a460e1b4e75f.png)

**Comment by tomchop** [comment]
Wow, 78 feeds is quite a number. Thanks a bunch for the (future) contribution! We do have a `/contrib` directory in which feeds from external contributions are being placed, but such a large volume might justify a separate repo where we can put all contributions.

Regarding the API keys, this can be done via Yeti's main config file (check out the [Contributing plugins](https://github.com/yeti-platform/yeti/tree/master/contrib#contributing-plugins) page on how to do this). You can also specify API keys for analytics in Yeti's UI, but this is more reserved to a per-user API key so that API quotas are used individually (besides, I assume you'd want all data from feeds available to all users of your Yeti instance).

Regarding performance, if you have 36 cores you could push the limits a bit further (the ones we have in the documentation are very conservative). I'm curious to know the number of workers past which performance starts to degrade. You could also decrease the frequency at which individual feeds are being refreshed (the 1-hour period was set rather arbitrarily, and I think this varies greatly per-feed; ideally we would like to have an algorithm determine the optimal refresh rate)

On a final note, if 80% of the feeds come from external contributions, we might want to rethink the way we present them to the user. Maybe we should display only those that are enabled? (the feature to enable / disable a feed already exists); or at least hide / group those that are disabled? Also, with 70+ feeds, it might be easier to start an instance with all feeds disabled and let the user choose which ones it wants to enable. This probably entails some more information on the feeds than what actually exists, such as relevance, amount of context, type of feed (spamlist, banking trojan C2, APT observables, etc.)... food for thought.

I'll close this issue once we've agreed on how / where to put these contributed feeds. Thanks again!

**Comment by darksheer** [comment]
No worries, happy to help as you have put a lot of effort into the project.  

For the feeds I have created, most have zero extra python dependencies and are simple to enable and execute (drop in feeds folder and let them go). 

For the sake of speed and simplicity, I'll separate them by folder (there are multiple feeds from the same 'source), write up the docs, and push to /contrib until a decision is made on the best way to handle them.  I would like to get your thoughts on them to make sure they work the way you intend (tagging, first_seen, last_seen, etc.) 

To me, having a sperate repo or just having them committed to core makes the most sense from a deployment methodology as it's less work moving files around.  I like the idea of having all feeds presented to the user and then the choice of which ones to enable/disable are made by the end user. 

Sound like a good place to start?

Performance wise, I can adjust any settings for ram/cpu/threads via the deployments I have.  I think where things are going to bottleneck will be MongoDB... I'm considering launching something like this reference architecture: https://aws.amazon.com/blogs/aws/mongodb-on-the-aws-cloud-new-quick-start-reference-deployment/ Feel free to ping me via my email vincent\.\passaro\@\gmail\.\com and I can go into it further. 

p.s. Any thoughts on creating a slack channel for the project?

**Comment by darksheer** [comment]
After reviewing the process of getting feeds from ```contrib/``` into public is a little bit cumbersome.  I tried getting the ThreatTracking feed setup, which is failing, but I belive that to be a Google API issue. 

Most of the feeds I built don't require any special configs, so they could be ingested directly, I'll submit the pull requests dropping them straight into core public and the can be approved/denied as you see fit.  

I'll try and get most of these over today after work.

**Comment by darksheer** [comment]
Initial pull request sent:

https://github.com/yeti-platform/yeti/pull/207

**Comment by tomchop** [comment]
Feeds with 0 external dependencies can probably go in core for now. That said a separate repo is still a good idea if we want to keep things a bit cleaner; we'd need to adjust the existing documentation to reflect this.

> After reviewing the process of getting feeds from contrib/ into public is a little bit cumbersome. I tried getting the ThreatTracking feed setup, which is failing, but I belive that to be a Google API issue.

Can you elaborate on that? Is it the process of documenting the feeds in `contrib/` that you find cumbersome or actually getting them to work with running instance?

I'll review #207 tonight, thanks a bunch!
