### ISSUE TITLE
stuck when access "system" & Feed update

### ISSUE THREAD

**Issue by njzy** [yeti-platform/yeti#220]
### Description
stuck when access "system" & Feed update

### Environment

| Question         | Answer
|------------------|--------------------
| Git commit       | 2df99e7f1fc7ec640f10463388150c471db6b3fc
| OS version       | Ubuntu 16.04
| Browser          | Chrome 63.0.3239.132

### Steps to Reproduce
1. Access http://localhost:5000
2. "Setting"-->"System"

#### Actual behavior
After clicking the page has been loading state, and then click on other pages did not respond, only to restart the application.
![image](https://user-images.githubusercontent.com/9823010/35332001-74924778-0144-11e8-9d75-b38e1e432320.png)

### Steps to Reproduce
1. Access http://localhost:5000
2. "Setting"-->"Dataflows"-->"Feed update"

#### Actual behavior
Ajax request is error,
![image](https://user-images.githubusercontent.com/9823010/35332189-0ea906f8-0145-11e8-9340-33e42e074e0c.png)

BTW:I use docker

**Comment by tomchop** [comment]
Sorry for the delayed response.

Issue 1 is very likely due to the fact that you're running a dev instance, which does not support concurrent web requests (python GIL). The "system" request takes a lot of time because it checks with locally running celery daemons and they may take a while to answer. Unfortunately, no other requests can be handled by Flask while this one is ongoing.

Issue 2 is a bit strange - I see no error here. If you've tried refreshing a feed right after requesting the "system" webpage, what I described above might be the issue.

**Comment by jmckinlay** [comment]
I am having the same problem, running YETI from /opt on Centos7 behind NGINX, feeds not updating, system page timing out - my first thought is it is a celery issue, when I run strace against
celery -A core.config.celeryctl.celery_app worker --loglevel=DEBUG -Q feeds -n feeds -Ofair -c 2 --purge

I get 
strace: Process 1736 attached
select(0, NULL, NULL, NULL, {0, 960695}) = 0 (Timeout)
select(0, NULL, NULL, NULL, {1, 0})     = 0 (Timeout)
select(0, NULL, NULL, NULL, {1, 0})     = 0 (Timeout)
select(0, NULL, NULL, NULL, {1, 0})     = 0 (Timeout)
select(0, NULL, NULL, NULL, {1, 0})     = 0 (Timeout)
select(0, NULL, NULL, NULL, {1, 0})     = 0 (Timeout)
select(0, NULL, NULL, NULL, {1, 0}^Cstrace: Process 1736 detached
 <detached ...>
