### ISSUE TITLE
Question: Requirements

### ISSUE THREAD

**Issue by chenerlich** [yeti-platform/yeti#268]
### Description
Is there a recommended requirements for running YETI on a server? I really want to integrate it in my environment.

Thanks

**Comment by tomchop** [comment]
It really depends on what amount of data you're thinking of ingesting. If you're not going to use feeds a lot / at all, you can do with a small instance. Otherwise I know @sebdraven has had success with 8 cores and 32 GB of RAM to run everything.

Storage-wise, mongodb is pretty efficient and from experience storing around 2M indicators takes less than 5 GB.

**Comment by chenerlich** [comment]
@tomchop Thanks!
I think it's worth writing in the docs.
On this issue (kinda): Have you had the chance to install the docker provided in github?
It failed to me..

**Comment by doomedraven** [comment]
i have 4 cores and 32gb ram and 10tb hdds
