### ISSUE TITLE
Question about yeti

### ISSUE THREAD

**Issue by 0x00xx** [yeti-platform/yeti#312]
Hey guys, I am sorry to post this here, but I did not find an email address to get in touch with just a single member.

I am studying computer science and currently doing my master thesis-.
In the thesis I am looking into enterprise architecture, which I want to combine with thread intelligence sharing platforms. During my research I came across your platform, and was wondering if someone could answer me some questions about it:
1) Which informations security processes (for example ISRM, ISMS) does your platform support? (If any)
2) Which import / export possibilities (including standards like TOGAF etc.) does your platform support?
3) Which data sources (external, internal, sensor data...) does your platform support?
4) Is it possible to exchange information between your platform and EA tools, or even integrate it?
5) Is your platform open source? (Well I guess, since it's on github :P )

This would help my master thesis alot!

Thanks in advance,
0x00xx

**Comment by tomchop** [comment]
Hey! No worries, GitHub issues are a good place to ask these questions, too. So to answer your questions:

1. Yeti does not support any specific "security process". It's just a datastore with ingestion / export capabilities.
2. The platform can import any kind of source, as long as you write a proper feed (i.e. Python code) for it. Out-of-the-box support is not enforced for any particular format, although we do offer shorthands for importing data from CSV, XML, and MISP sources. [Yeti v2](https://github.com/yeti-platform/TibetanBrownBear) also supports TAXII.
3. These are all included in https://github.com/yeti-platform/yeti/tree/master/plugins/feeds/public
4. It's "possible" I'd say, since Yeti has a pretty powerful API and can therefore easily talk to other systems. But there is no out of the box integration for this.
5. You got it :)

Feel free to reopen if you have any other questions!
