### ISSUE TITLE
help with jinja template - question

### ISSUE THREAD

**Issue by cucx** [yeti-platform/yeti#318]
HI! im trying to see if any `datetime` or  `now` keywords  are defined in a template for jinja. In 
`/node_modules/codemirror/mode/jinja2/jinja2.js` it indicates a `now` as a defined keyword , however when i try to add that to a template i get `ERROR executing export: 'now' is undefined`. 

Do you know if this is indeed supported? (eg to simply get a template that can export the last 24 hours `{% if (now-obs.created).days>=1 %}` )

**Comment by tomchop** [comment]
According to https://github.com/audreyr/cookiecutter/issues/155#issuecomment-207261905, datetime functions are included in jinja as of 1.4.0. See examples here: https://github.com/hackebrot/jinja2-time

@p-l- 's comment is very relevant however. Currently exporters are mainly based on tag selection, and in order to export the most recent ones one would need to write a custom exporter (which shouldn't be very hard to do but ins't documented)

**Comment by cucx** [comment]
>>According to audreyr/cookiecutter#155 (comment), datetime functions are included in jinja as of 1.4.0. See examples here: https://github.com/hackebrot/jinja2-time

Thx! Oddly i still cant seem to get it to recognised the defined `now` even with just giving a simple `{% now 'utc' - 'minutes=11' %}` . I'll try and work it out thanks again. 

>>@p-l- 's comment is very relevant however. Currently exporters are mainly based on tag selection, and in order to export the most recent ones one would need to write a custom exporter (which shouldn't be very hard to do but ins't documented)

Yes! fully aware, i'm currently simply pulling what i need out of the mongodb so that works fine, but would have been nicer to  have this done in a template
