### ISSUE TITLE
How to Create Custom Feed by using "File" as Source input

### ISSUE THREAD

**Issue by s-shubh** [yeti-platform/yeti#340]
### Environment

| Question         | Answer
|------------------|--------------------
| OS version       | CentOS 7
| Browser          | Chrome Latest

Hi Folks, 

I am having a list of files; those contains blacklisted IP along with its category which I want to configure as feed source in Yeti. As per the documentation; Source can only be an HTTP request to download such kind of data.  Could it be possible to use downloaded file or updated file as a Source. I have been customizing this file for my own purpose. Its threat sources would be different which also limits their API use. 

This file will be set to update on daily bases but I could not parse it through YETI. 

Find the format of file1 :

----
IP Category
---
OR 
---
URL Category
----

Please let me know whether it could be possible and if yes then help to parse it through Yeti...!

Shubham Shah

**Comment by tomchop** [comment]
I saw your message on the mailing list, let's keep the discussion going here so that it's easily referenced.

You can create a feed with any kind of source as you want, as long as your python code can access it. Most of the time it's URLs, so we've created "helpers" that deal with common feed formats (CSV / XML, etc.), but you don't *have* to use them.

If the files are on your local server, then it's easy to create a feed to open the file and read stuff from it.

**Comment by shubhamblackstratus** [comment]
Hey, 

Thank you for an information. 

I am little bit new to python. I was just taking a reference from your examples. Could you pleas help me in this ?

**Comment by sebdraven** [comment]
You want to sync one file ? or directory ?

**Comment by shubhamblackstratus** [comment]
I am little bit new in python, please suggest me how can get feeds from
file rather than url.  This file updates every day on the execution of some
urls which i can not share in that yeti config.

**Comment by doomedraven** [comment]
see any feed, and in 

```
    def update(self):
        for line in open(path_to_your_file, "r").read():# or readlines, you know better how to handle your file 
            self.analyze(line)
```
