### ISSUE TITLE
systemctl daemon-reload  No such file or directory

### ISSUE THREAD

**Issue by jooeji** [yeti-platform/yeti#47]
RUN systemctl daemon-reload
---> Running in 7a7a7661c963
Failed to connect to bus: No such file or directory
os:ubuntu 16.04

**Comment by jooeji** [comment]
RUN systemctl daemon-reload
 ---> Running in 7a7a7661c963
Failed to connect to bus: No such file or directory
os:ubuntu 16.04

**Comment by tomchop** [comment]
Unfortunately I need more info than that to help you. How did you install Yeti? Can you print the full error message of what you're seeing, as well as the exact commands you entered? Thanks!

**Comment by jooeji** [comment]
I refer the bootstrap.sh  to modify Dockerfile ,
but ***RUN systemctl daemon-reload
---> Running in 7a7a7661c963
Failed to connect to bus: No such file or directory***

**Comment by tomchop** [comment]
I understand you're trying to build a dockerfile? Can you show me its whole contents?

**Comment by jooeji** [comment]
![1](https://cloud.githubusercontent.com/assets/12831513/25030451/95715ed0-20f7-11e7-8ac3-19c33e3da081.png)
![2](https://cloud.githubusercontent.com/assets/12831513/25030455/978c5f80-20f7-11e7-994c-4f22a0d743b1.png)
The dockerfile that i build ,but the docker images was not build  succeed because of 【RUN systemctl daemon-reload
---> Running in 7a7a7661c963
Failed to connect to bus: No such file or directory】

**Comment by tomchop** [comment]
Thanks for the detailed info! Two things right off the bat: 

* I see you're calling `/start.sh`. For some reason this seems to work even though there is no `start.sh` file in `/`. You seem to be copying it to `/opt/start.sh`
* I'm not a docker expert so I'm not really familiar with the difference between the `CMD` and `RUN` directives. `systemctl` is a binary in `/bin`, so you might be better off by calling `/bin/systemctl` instead of just `systemctl`. Also, you might need to have `sudo` privileges for that, and I'm not sure the `CMD` directive ensures that.

Can you try adjusting that and see what happens?

**Comment by gaelmuller** [comment]
No response to the last comment, so I'm closing this issue. Do not hesitate to reopen if needed.
