### ISSUE TITLE
How to update Yeti instance?

### ISSUE THREAD

**Issue by nebu10uz** [yeti-platform/yeti#51]
### Question
Can you recommend on how to update the Yeti instance with the latest version without losing your data such as observables investigations, etc.?

**Comment by tomchop** [comment]
You can just update yeti using `git pull` from the directory in which you `git clone`d Yeti. I expect breaking changes to be pretty rare at this point, especially since the database is schema-less.

That said, I would recommend backing up your database before any updates. This has yet to be added to the documentation. Thanks for bringing it up!
