### ISSUE TITLE
Export and Import of investigations

### ISSUE THREAD

**Issue by gamelinux** [yeti-platform/yeti#59]
### Description
1) Export
Be able to export investigations in a structural way (json etc).
The export should contain at least the data displayed in the graph, probably with options to include descriptions, tags (include/exclude tags?), observables, context, TLP (Traffic Light Protocol (if the concept is ever implemented), etc.

2) Import
Be able to import an investigation (previously exported from yeti). Maybe with options to add a tag or source (like a feed) etc. (and maybe import it with a TLP constraint to the user importing it? if the TLP concept is ever implemented).

**Comment by gaelmuller** [comment]
Investigation export is already possible by using the API:

```
http -j 'http://localhost:5000/api/investigation/<ID>'
```

The API might even allow import in some conditions but I would advise against it as these API endpoints are not currently meant for this use case.

There is currently no plan to improve investigation export/import from the Web interface or API, but I will leave this issue open so that people can 👍 or even implement it.
