### ISSUE TITLE
Question: Is it somehow possible that Yeti connects to DNS Port 53 of known bad IPs/domains?

### ISSUE THREAD

**Issue by certrik** [yeti-platform/yeti#601]
Can it somehow be that Yeti or some connector/worker connects to sinkholed domains? Just wondering.

**Comment by certrik** [comment]
Found it myself. Yeti does automatically resolve the hostnames of domains from feeds. 
Don't know if this is a good idea.

**Comment by tomchop** [comment]
It does hostname resolution yes, but shouldn't be opening connections. I understand that this might be unwanted behavior.  You can disabled the DNS resolution analytics (which is enabled by default; maybe we should change this?)

**Comment by certrik** [comment]
Well in my case I was contacted by CERT that my IP apparently was resolving bad domains which where sinkholed and that I potentially was infected by malware. So probably disable it by default and place a disclaimer that something like that could happen.

**Comment by dumprop** [comment]
> Found it myself. Yeti does automatically resolve the hostnames of domains from feeds.
> Don't know if this is a good idea.

It can be helpful if you need IP addresses of malware domains. If malware uses ESNI there no way of detection by domain, so IPs are left (fortunately on malware normally no legitimate services)
Currently that very rarely now, but it can be changed in near future  (because it near about TLSv1.3, which are already released)
I think that should be enabled, but only for selected domain or trusted feed (ie if you have own feed with dynamic domains)
