### ISSUE TITLE
Entity missing pre-creation tagged observables. 

### ISSUE THREAD

**Issue by ghost** [yeti-platform/yeti#96]
### Description
Entity not showing tagged observables in "observables" tab when creating entity after observable has already been tagged. 

Possible to add this sync ability after creating a new entity? Or perhaps I'm not catching something from the documentation that states how to do that already. Any help would be great! 

### Environment

| Question         | Answer
|------------------|--------------------
| Git commit       | 5e6a2ad623f465fa370f6d0141e7300674f85b9f
| OS version       | Ubuntu 14
| Browser          | Chrome 59.0.3071.86

### Steps to Reproduce
1. create observable with tag "testing"
2. create entity with 'Tags that will link to this entity' of "testing"
3. Refresh page - observables not visible in this entity.
4. create new observable tagged as "testing"
5. Look at entity - shows only the second observable. 

#### Expected behavior
A new entity to show all pre-created tagged observables. 

#### Actual behavior
Pre-entity tagged observables do not show up within the entity. Until tag is removed and readded into the observable.

**Comment by luckyb56** [comment]
+1
Mine slightly different use-case but same result as @WArurrt 
#### Steps to Reproduce
1. Create entity with tag 'someone'
2. Create observable with tag 'someone'
3. Delete the entity
4. Create new entity with tag 'someone'

#### Expected behavior
The new entity should show association with the observables with same tag 'someone'

#### Actual behavior
The new entity doesn't show any association with the observable with same tag

Upon editing the observable and just clicking on save, associated with newly created entity.

**Comment by tomchop** [comment]
Interesting use-case! Will note this and try to push a fix soon.

**Comment by WArurrt** [comment]
Awesome, thank you!

**Comment by tomchop** [comment]
So, one way to implement this is to add an Inline analytics that will trigger when the entity is added. This feature is implemented in #84, once it will be merged we can create an analytics that will go through every added entity and link any pending observables to it asynchronously.
