### ISSUE TITLE
Feature Request: Local markdown images 

### ISSUE THREAD

**Issue by WArurrt** [yeti-platform/yeti#97]
It would be great to add images (in entity descriptions) with the markdown method of typing ![]() to be given an add image button. 

Thanks!

**Comment by gaelmuller** [comment]
We will not be adding an "add image button" because we do not have this kind of control over our markdown editor.

We did however built this feature into Yeti. You can add a local image to your markdown by copy-pasting it directly in the editor or using drag-an-drop.

Please note that this feature was broken a week ago and I just fixed it, so make sure to use the last version if it does not seem to work.

**Comment by WArurrt** [comment]
Ah perfect, thank you! My apologies on missing the previous documentation on it as well.

**Comment by WArurrt** [comment]
Looks to not be working after a fresh update. I feel like it may be permissions related - any thoughts on how to confirm?
